### Send POST request with json body
PUT  http://localhost:3000/api/users
Content-Type: application/json

{
  "id": 1,
  "email": "john@example.com",
  "password": "new-password",
  "role": "admin"
}


