@startuml
'https://plantuml.com/class-diagram

!include https://raw.githubusercontent.com/plantuml/plantuml/master/themes/puml-theme-mars.puml

Class "Users" as Users{
-id_users: Integer
-first_name: String
-last_name: String
-age: Integer
-birthday: DATE
-email: String
-passWord: String
}

/'abstract class "Users" as u2{}'/

Enum Status{
    Player
    Admin
}

Class Player{
-status: Status
}
Class Admin{
-status: Status
}

Class Entites{
- id_entite: Integer
- nom_entite: String
- categorie: String
- is_ajoute: Boolean
}

Class Game{
-id_game: Integer
-id_first_term: Integer
-id_second_term: Integer
-id_player: Integer
-nb_fois_jouer: Integer
-is_ajoute: Integer
}

Class DifferenceInGame{
    - idTerme1: Integer
    - idTerme2: Integer
    - idDiff: Integer
}

Class Differences{
    -id_diff: Integer
    -type_diff: type_difference
    -valeur_diff: Integer
}

Enum type_difference{
    Lieu 
    Caracteristique
    Couleur
    ...
}



class GamesPlayed{
-id_game: Integer
-id_player: Integer
-startplay: Date
-is_fini: Boolean
-pourcentage: Intger
-score: Integer
}


Users <|-- Player
Users "1..*"  o-- "1"Game: create >
Users <|--Admin


Differences"1" - "*"Game : contain <
(Differences, Game)"*" -- DifferenceInGame


Game "2" - "1..*"Entites : contain <

Game "*" - "1"Player : play <
(Player, Game)"*" --  GamesPlayed



@enduml
