@startuml
'https://plantuml.com/class-diagram

!include https://raw.githubusercontent.com/plantuml/plantuml/master/themes/puml-theme-mars.puml

Class "Users" as Users{
-id_users: Integer
-first_name: String
-last_name: String
-age: Integer
-born: Date
-email: String
-passWord: String
}

/'abstract class "Users" as u2{}'/

Class Player{
-status: Boolean
}
Class Admin{}

Class Entite{
- id_entite: Integer
- nom_entite: String
- categorie: String
- is_ajoute: Integer
}

Class Relations{
- id_relation
- first_term: String
- type_relation: String
- second_term: String
- valeur_relation: String
}


Class Game{
-id_game: Integer

-first_term: String
-second_term: String

-nb_fois_jouer: Integer
}

Class RelationInGame{
- idRelation: Integer
- idGame: Integer
}



class GamesPlayed{
-id: Integer
-startplay: Date
-score: Integer
-terme: String
}


Users <|-- Player
Users "1..*"  o-- "1"Game: create >
Users <|--Admin

Game "*" - "*"Relations : contain <
(Relations, Game)"*" --  RelationInGame

Game "*" - "1"Player : play <
(Player, Game)"*" --  GamesPlayed



@enduml
